spring.application.name=financeai
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jackson.default-property-inclusion=non_null

# URL del microservicio de Ciencia de Datos
python.service.base-url=${ML_API_URL:http://localhost:5000/api/v1}

# Conexión a la base de datos PostgreSQL (con fallbacks para desarrollo local)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fintech_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:fintech_db123}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# "none" previene que Hibernate modifique tus tablas para evitar conflictos con el init.sql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true