spring.application.name=financeai
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jackson.default-property-inclusion=non_null

# URL del microservicio de Ciencia de Datos
python.service.base-url=http://data-science:5000/api/v1